### ISSUE TITLE
[front] 채팅 관련 기능 필수 구현 TODOLIST

### ISSUE THREAD

**Issue by parktest0325** [3DPong/transcendence#159]
### 프론트 구현 
- [x] 소켓연결과 알람관련 기능을 최상단으로 변경(notifySocket도 최상단으로)
- [ ] @ 알람 컴포넌트 구현 (초대, 밴, 킥 알람관련 기능) 
- [x] 채팅방 상세에서 네비게이트 히스토리 지우기 
- [x] 채팅방 상세 로딩중일때 그냥 /channels로 이동시켜버리기 => DM에서 방이 안만들어졌는데 새로고침하면 잘못된 동작을함

#### 현재 문제점 (정리중)
1. DM은 create일때 초대되면 안된다. 
  이유 1. 탑5개 만 보여지는 상황: 만약 이미 dm 채팅방이 존재하면 메시지를 보내도 채널리스트에 추가될 수 없다. (프론트에선 정보가 없음) 
  이유 2. 메시지도 안보냈는데 리스트에 추가되는것도 이상함
  => 채팅방과 달리 메시지를 보낼때 리스트에 없다면 추가되는 방식
2. 탑 5개만 보여지면 안된다.
3. DM 이 채널리스트에 없는경우 상세페이지에서 볼 수 없음
=> channels를 최상단으로 올려서 관리. DM 보낼때 channels에 값을 집어넣고 channels를 처음 fetch할때 겹치는 데이터를 제외하고 set 함  

- [x] dm 메시지 보내기 버튼 => 채널 정보 리턴 + 해당 채팅 상세로 이동
   api 요청 -> 응답 데이터로 채널아이디리턴 -> 프론트엔드에서 해당 DM 채널 URL로 이동 
   현재 문제점 : owner가 보내짐. 상대방의 닉네임등이 오너로 보내져야함.
- [x] DM 메시지를 보내고나면 상대방은 invite 같은 알람 이벤트가 필요함 여기서는 채널 타입 메시지가 필요함 이때 초대됨
- [x] DM 에서 users 요청시 role을 user로 고정한 first_user, second_user 유저 리스트 응답 (channelId/dm/users)
=> 컴포넌트에서 dm 타입체크 처리가 힘들어서 그냥 같은 api로 가능한지?

### 게임초대 구현
게임 초대 => 채널아이디를 서버에 보내줌 => 서버에서는 소켓으로 채널아이디, 게임아이디 응답 => on 하고 있다가 게임 초대 메시지 객체를 만들어서 챗소켓으로 emit => 서버에서는 일반 채팅메시지처럼 관리 

초대메시지를 보내면 초대 보낸사람은 game으로 리다이렉트 후 큐에서 대기 (큐는 채널아이디, 게임아이디로 구분)
게임하기 누른 사람은 같은 큐로 이동
관전하기 누른 사람은 관전

- [x] 메시지 방식으로 변경. => 메시지에 type을 추가해서 game, chat 구분 
=> game인 경우 메시지가 객체임, chat인경우 메시지
- [x] 메시지 렌더링 구현 (타입에 따라 메시지 렌더링 방식 변경) 참여하기와 관전하기 각각 이벤트 연결
- [ ] 초대, 참여, 관전 에러 처리 (소켓 에러로 서버에서 보내면 받아서 사용)
- [x] 초대버튼을 누르면 게임모드선택으로 이동 => 게임모드선택이 끝나면 큐에서 대기
- [x] 참여 버튼을 누르면 큐에서 대기 
- [x] 관전 버튼을 눌렀을때?

### 추가 요청 및 토의
- 메시지에 게임 모드도 표시하기 위해 inviteData 에 gameMode 추가 필요
- chatJoin 에서 처음 초대메시지를 만든사람은 gameId 외 나머지, 채팅메시지에서 게임하기 버튼 눌러서 2p 로 들어온 사람은 gameId만 전달
- onGameInvite는 맨처음 초대메시지를 보낸사람(channelId, roomType, gameType) 을 같이 전송했을때만 emit 필요. 지금은 초대받은 사람에게도 이벤트가 전달됨

**Comment by kyu-baek** [comment]
backend 구현 사항
1. dm 나가기
2. dm 채널에 대한 정보를 받을 때 (dm create or invite or my list) 당사자의 정보가 아닌 상대방의 정보를 받을 수 있게 하기
